name: iOS Tips Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test default scheme using iPhone/iPad simulator
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      # - name: Select Xcode Version
      #   run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Run Tests
        run: |
          xcodebuild test -project Tips.xcodeproj -scheme Tips -resultBundlePath TestResults -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14"

      # - name: Process Test Results
      #   uses: kishikawakatsumi/xcresulttool@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     path: TestResults.xcresult
      #   if: ${{ success() || failure() }}
