name: iOS Tips Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test default scheme using iPhone/iPad simulator
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

#      - name: Select Xcode Version
#        run: sudo xcode-select -s /Applications/Xcode_12.4.app # Replace with your required Xcode version

      - name: Run Tests
        run: |
          xcodebuild test -project Tips.xcodeproj -scheme Tips -destination "platform=iOS Simulator,name=iPhone 14"
      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
        if: success() || failure()
