name: iOS Tips Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build and Test default scheme using iPhone/iPad simulator
    runs-on: macos-latest
     steps:
    - uses: actions/checkout@v2
    - name: Set up Xcode
      uses: actions/setup-xcode@v1
      with:
        xcode-version: latest 
         name: Run Tests
      run: xcodebuild test -project Tips.xcodeproj -scheme Tips -destination 'platform=iOS Simulator,name=iPhone 15,OS=16.0'
